### ISSUE TITLE
Logstash UI

### ISSUE THREAD

**Issue by outrunthewolf** [denibertovic/logstash-dockerfile#3]
Is the UI available? I can't seem to access it.

**Comment by ryanjm** [comment]
Same here.

**Comment by denibertovic** [comment]
@ryanjm @outrunthewolf sorry for the late reply but yes it's available on port 9292. You do need to map it to a port on the host though.

However I believe the recommended way is to use Kibana, for a easier (one-command-ish) way to bring up the whole ELK stack you might want to to take a look here: https://github.com/denibertovic/elk-stack-docker
